{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cyberbox.fullname" . }}-agent
  labels:
    {{- include "cyberbox.labels" . | nindent 4 }}
    {{- include "cyberbox.selectorLabels" (dict "root" . "component" "agent") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cyberbox.selectorLabels" (dict "root" . "component" "agent") | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.agent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cyberbox.labels" . | nindent 8 }}
        {{- include "cyberbox.selectorLabels" (dict "root" . "component" "agent") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cyberbox.serviceAccountName" . }}
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: {{ include "cyberbox.image" (dict "root" . "component" "agent" "overrideRepo" .Values.agent.image.repository) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "cyberbox.fullname" . }}-config
          env:
            - name: CYBERBOX_COLLECTOR_URL
              value: "http://{{ include "cyberbox.fullname" . }}-collector:{{ .Values.collector.ports.tcp }}"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: queue
              mountPath: /var/lib/cyberbox/queue
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
        - name: queue
          emptyDir:
            sizeLimit: 512Mi
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
