{{- if .Values.clickhouse.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    {{- include "cyberbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
  selector:
    app.kubernetes.io/component: clickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-headless
  labels:
    {{- include "cyberbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
  selector:
    app.kubernetes.io/component: clickhouse
{{- end }}
