{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cyberbox.fullname" . }}
  labels:
    {{- include "cyberbox.labels" . | nindent 4 }}
  annotations:
    {{- if eq (.Values.ingress.className | default "") "alb" }}
    # AWS ALB Ingress Controller
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/group.name: cyberbox
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    {{- end }}
    {{- end }}
    {{- if eq (.Values.ingress.className | default "") "nginx" }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if and .Values.ingress.tls (not .Values.ingress.certificateArn) }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "cyberbox.fullname" . }}-api
                port:
                  number: 8080
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: {{ include "cyberbox.fullname" . }}-api
                port:
                  number: 8080
          - path: /metrics
            pathType: Exact
            backend:
              service:
                name: {{ include "cyberbox.fullname" . }}-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cyberbox.fullname" . }}-ui
                port:
                  number: 3000
{{- end }}
