{{- if .Values.prometheus.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cyberbox.fullname" . }}-api
  labels:
    {{- include "cyberbox.labels" . | nindent 4 }}
    {{- include "cyberbox.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cyberbox.selectorLabels" (dict "root" . "component" "api") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
