apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cyberbox-app-egress-core
  namespace: cyberbox
spec:
  podSelector:
    matchLabels:
      security.cyberbox.io/tier: app
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cyberbox
          podSelector:
            matchLabels:
              app: redpanda
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cyberbox
          podSelector:
            matchLabels:
              clickhouse.altinity.com/chi: cyberbox-clickhouse
      ports:
        - protocol: TCP
          port: 8123
        - protocol: TCP
          port: 9000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cyberbox
          podSelector:
            matchLabels:
              app: minio
      ports:
        - protocol: TCP
          port: 9000
