apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cyberbox-api-ingress
  namespace: cyberbox
spec:
  podSelector:
    matchLabels:
      app: cyberbox-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
