apiVersion: v1
kind: Service
metadata:
  name: redpanda-headless
  namespace: cyberbox
spec:
  clusterIP: None
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: rpc
      port: 33145
      targetPort: 33145
